# Generated by Django 3.2.13 on 2022-04-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='Audio',
        ),
    ]
