# Generated by Django 3.2.13 on 2022-04-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_profile_audio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audio',
            new_name='Audio_upload',
        ),
    ]
