# Generated by Django 3.2.13 on 2022-04-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_audio_audio_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ai_bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('Bot_Sound', models.FileField(upload_to='')),
            ],
        ),
    ]
