# Generated by Django 3.2.13 on 2022-04-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ai_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AudioFront', models.FileField(upload_to='')),
            ],
        ),
    ]
