# Generated by Django 3.2.13 on 2022-04-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_audioshow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioShow',
        ),
    ]
