# Generated by Django 3.2.13 on 2022-05-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_audioshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoSepration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawVideo', models.FileField(upload_to='')),
            ],
        ),
    ]
